train_inference:
  model_features:
    # - mean_ear
    # - mean_blink_time
    - ear
    - mar
    - pitch
    - perclos
    # - blinks_per_minute
    - current_time_closed_eyes
    - yawns_per_minute
    - head_nods_per_minute
    # - open_eyes
    # - head_nod
    # - yawn

  model: 'lgb'
  optuna: False

metric_obtention:
  
  periodical_data_max_values: 600

  detect_eyes: True
  detect_mouth: False
  detect_head: False

  eye_closure_method: 2
  eye_closure_threshold: 0.2
  main_threshold_perc: 0.75
  gray_zone_perc: 0.08
  num_ear_past_frames: 200
  eye_alpha_val: 0.35

  pose_angles_detection_frequency: 3
  pitch_method: 1
  head_nod_threshold: 45
  head_nod_threshold_perc: 0.85
  num_past_frames_pitch: 1
  gray_zone_pitch: 0.15
  head_nod_y_min_threshold: 0.1
  num_frames_nose_tip_y: 100
  num_frames_new_head_nod: 15


  num_frames_dynamic_avg: 1800
  num_frames_lag_ignore: 15

  mouth_closure_method: 2
  mouth_yawn_threshold: 0.4
  gray_zone_mouth: 0.05
  num_past_frames_mouth: 40

  yawn_y_min_threshold: 0.1
  num_frames_mouth_top_y: 100
  num_frames_new_yawn: 15

  min_eye_vertical_distance: 10
  eye_image_size: 227
  period_length: 1
  min_num_frames: 1800
  
  subjects:
    train: []
      # - '001'
      # - '002'
      # - '005'
      # - '006'
      # - '008'
      # - '009'
      # - '012' # este
      # - '013'
      # - '015'
      # - '020'
      # - '023'
      # - '024'
      # - '031' # este
      # - '032'
      # - '033'
      # - '034'
      # - '035'
      # - '036'
    test: 
      # - '003'
      # - '010'
      # - '011'
      # - '014'
      # - '016'
      # - '017'
      # - '018'
      # - '019'
      # - '021'
      # - '025'
      # - '027'
      # - '028'
      # - '029'
      # - '037'
  scenarios:
    # - glasses
    # - night_noglasses
    # - nightglasses
    - noglasses
    # - sunglasses
  states:
    - nonsleepy
    - sleepy
    - slowBlinkWithNodding
    - yawning
    - mix

  metrics_to_obtain:
    - ear
    - ear1
    - ear2
    - ear3
    - ear4
    - left_iris_diameter
    - right_iris_diameter
    - left_euclidean_iris_diameter
    - right_euclidean_iris_diameter
    - mar
    - mar1
    - mar2
    - yaw
    - yaw1
    - yaw2
    - pitch
    - pitch1
    - pitch2 
    - nose_tip_y
    - frame_count
    - mean_ear
    - perclos
    - closed_eye_frame_count
    - current_time_closed_eyes
    - blink_frequency
    - mean_blink_time
    - blinks_per_minute
    - num_blinks
    - num_yawns
    - yawns_per_minute
    - head_nod_count
    - head_nods_per_minute
    - head_nod
    - yawn
    - open_eyes