train_inference:
  model_features:
    - perclos
    - blink_frequency
    - current_time_closed_eyes
    - mean_ear

  model: 'lgb'
  optuna: False

metric_obtention:
  min_eye_vertical_distance: 10
  eye_image_size: 227
  period_length: 1
  min_num_frames: 1800
  metrics_to_obtain:
    - frame_count
    - mean_ear
    - perclos
    - closed_eye_frame_count
    - current_time_closed_eyes
    - blink_frequency
    - blinks_per_minute
    - num_blinks
    - num_yawns
    - yawns_per_minute
    - mean_left_iris_diameter
